version: '2.2'

services:
  openhab-sse-test:
    image: openhab/openhab:latest
    container_name: openhab-sse-test
    restart: unless-stopped
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "./openhab/userdata:/openhab/userdata"
      - "./openhab/addons:/openhab/addons"
      - "./openhab/config:/openhab/conf"
    environment:
      OPENHAB_HTTP_PORT: "8080"
      OPENHAB_HTTPS_PORT: "8443"
      EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Berlin"
      VIRTUAL_HOST: "test.steilergroup.net"
      VIRTUAL_PORT: "8080"
  node-sse-test:
    image: "node:8"
    container_name: node-sse-test
    user: "node"
    working_dir: /home/node/app
    environment:
      NODE_ENV: "production"
    volumes:
      - ./node-src:/home/node/app
    expose:
      - "8081"
    command: "npm start"